data_seed: 42
exp_seed: 42
dataset: 'correlated' # correlated or random
item_count: 30
log_diversity: True
log_genotypes: True
print_interval: 10
n_generations: 15000
early_stopping: 1000
mutation_probability: 0.3
lattice_size: 12
